######################################################################
##
## Filename: uart_clk.udo
## Created on: Tue Jun 19 14:09:16 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
