######################################################################
##
## Filename: uart_clk_test.udo
## Created on: Tue Jun 19 14:11:44 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
